version: '3'
services:
  app:
    build:
      context: '.'
      args:
        uid: 1000
        gid: 1000
    environment:
      TZ: Asia/Tokyo
    working_dir: /usr/src/rparams
    volumes:
      - .:/usr/src/rparams
      - ./vendor/bundle:/usr/local/bundle
