name: RSpec

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rails-version: ['6.0', '5.2']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install dependencies
      run: sudo apt-get install libsqlite3-dev
    - name: Build and test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.rails-version }}.gemfile
