name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rails-version: ['6.1', '6.0', '5.2']
        ruby-version: ['3.0.6', '2.7.8', '2.6.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Install dependencies
      run: sudo apt-get install libsqlite3-dev
    - name: Build and test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.rails-version }}.gemfile
